language: node_js
node_js:
  - node

deploy:
  provider: heroku
  api_key:
    secure: F4qiyroB0rYl/4Q7PIJp0aQMklfmLtA0vN1jRUvinDIzu6cv0ig0sx473Nmo3z7/DOGvyv5gwTq47CPHMU6rM4ysVDjMBnGoZ4J+jwWGKzwbDuyjYSflSV+rfv/DTIydPpWYwaYWI4rPb9z5zZydMLSr0LzbiUwVAA/izf072h1lLv60suKVK38spDdHu+lPkTZNfXwL/3IhaL7fGIsEisuAmASj2t6XYR3YXIYjAcFJtBcBRIHSpuJsTg/43UG4ZXDBWJ7GC/sgX54OH8l8jY+xA783TQx8wesXbc/LyhD1/f3fY8jTweMtbTHM/fpHOQ6QDP8E1qFqW6oXpfhqzLHEr3a+WNpDXAL583jzwdlY7Na4ba/W4pOseo20GtSy5YvWhME1Qz5qabX6IEPvoKAAgBXQKHL1eKrtnZ+mrrDFy/Tov5qd3LMSAvKiOggrzJOMaguKj6rNn3X7A5AX/f2wCxfT3QVFCVfDmnxwA5l4ceuYvGwOLmiFxNERRDYISZFPP4kkFhyCqVp0r8taIX86Bm0aMo7SUMjBih1MMg3SupfmpuBQD/BtlnzRrrxIBg4JtLOFXYGrzX5RINQAhGrVWCxxck4N9/DBqChqCbSQo79/vWfgJ6MW80LaYxfuUpYCWCup48lhXNw1NQCAU4m2xoflBdz2vBGuZaSvJQQ=
  app:
    master: izakaya-release
    development: izakaya-staging
  run:
    - "npm start"

notifications:
  slack:
    rooms:
      secure: nmRoHenM1CRQQ0/ZV4jX3Zv9k8enw9X/oBP2Ux/WOSgSm6RuY+c1j30/yxtA67r142Ql/uPhRDCZ6yl+MExPG+evwjJJv/bQyOdCvL+or51AOLBDllvB0dbFfD3b6R1m+AoJOuxIUQRfrsMVpiZIoWxrIzauM+0egFRUAcY5vaIbbNrA+U7ucngD33+XhMLSMLIb8/2EQOeKcyXBdMBARzcMhg2EvgKVk9G1VBxrU0rQHBNWsmPOMtas5Ai5+9oAtGYNcM7kquCZemzdOEI48UZCeFsDUug02vikTq4sdDeh7+9N9tZdfJ7VVv3rrJnQwaMB8OfhR+bWYLjfINyM67DRAlqaDKqC/JAY4WYubTJ7h6G7Ys3KlrO4XHWNYMzJVMNyYhdWmLsG3pw5ZGcWeVUwbx0jVuGAhzQLzn5BQKAGIHeq4cOAjGSnNU2CtzHzXoovZ1xqVdbIB1Wd0d9/tfwbR+kaB2r0gskuJyTOgrxvy0dbRW6gvE79chFDf580VCZ4qd8XlBpd7ea67aUb9xveQMAVkQb48AwLfGIIIApXK41qnmHXaWm+aTdBvHIhmlXf+y4op5kK1JxwWx2cMl8zxCMot6uumIiIWz5UzVrUrM8VpXuCpZgixjubAv7i2Hy/bwR7RGF3wzaff+X/mPA7WFOYP0bfX8bj8L1/qvo=
